export const departments = [
  "Antioquia",
  "Bogotá D.C.",
  "Valle del Cauca",
  "Cundinamarca",
  "Atlántico",
  "Santander",
  "Bolívar",
  "Nariño",
  "Caldas",
  "Risaralda",
  "Quindío",
  "Tolima",
  "Huila",
  "Magdalena",
  "Cesar",
  "Caquetá",
  "Putumayo",
  "Arauca",
  "Boyacá",
  "Casanare",
  "Vaupés",
  "Guaviare",
  "Guainía",
  "San Andrés y Providencia",
];

export const citiesByDepartment: Record<string, string[]> = {
  Antioquia: ["Medellín", "Bello", "Envigado", "Itagüí", "Sabaneta", "La Estrella", "Copacabana", "El Retiro", "Rionegro"],
  "Bogotá D.C.": ["Bogotá"],
  "Valle del Cauca": ["Cali", "Palmira", "Buenaventura", "Tuluá", "Buga", "Yumbo", "Candelaria", "El Cerrito"],
  Cundinamarca: ["Soacha", "Chocontá", "Zipaquirá", "Facatativá", "Cota", "La Calera", "Girardot"],
  Atlántico: ["Barranquilla", "Soledad", "Malambo", "Puerto Colombia", "Sabanagrande"],
  Santander: ["Bucaramanga", "Floridablanca", "Barrancabermeja", "Girón", "Piedecuesta"],
  Bolívar: ["Cartagena", "Magangué", "Turbaco", "El Carmen de Bolívar", "San Jacinto"],
  Nariño: ["Pasto", "Tumaco", "Ipiales", "Portezuelo", "La Unión"],
  Caldas: ["Manizales", "Villamaría", "Chinchiná", "Palestina", "Neira"],
  Risaralda: ["Pereira", "Dosquebradas", "La Virginia", "Santa Rosa de Cabal", "Apía"],
  Quindío: ["Armenia", "Circasia", "Calarcá", "Montenegro", "Salento"],
  Tolima: ["Ibagué", "Espinal", "Honda", "Lérida", "Cajamarca"],
  Huila: ["Neiva", "Pitalito", "La Plata", "Campoalegre", "Garzón"],
  Magdalena: ["Santa Marta", "Ciénaga", "El Banco", "Fundación", "Aracataca"],
  Cesar: ["Valledupar", "La Paz", "Codazzi", "San Diego", "Gamarra"],
  Caquetá: ["Florencia", "Montenegro", "El Doncello", "La Montañita", "San Vicente del Caguán"],
  Putumayo: ["Mocoa", "Puerto Asís", "Villagarzón", "Santiago", "Orito"],
  Arauca: ["Arauca", "Saravena", "Tame", "Fortul", "Cravo Norte"],
  Boyacá: ["Tunja", "Duitama", "Sogamoso", "Paipa", "Chiquinquirá"],
  Casanare: ["Yopal", "Aguazul", "Tauramena", "Sácama", "Hato Corozal"],
  Vaupés: ["Mitú", "Caruru", "Pacoa", "Cacarica", "Vaupés"],
  Guaviare: ["San José del Guaviare", "Miraflores", "El Retorno", "Calamar", "Guaviare"],
  Guainía: ["Inírida", "Barranco Minas", "La Guadalupe", "San Felipe", "Cacahual"],
  "San Andrés y Providencia": ["San Andrés", "Providencia"],
};
